matrix:
  - name: Markdown
    sources:
      - '**/*.md'
    exclude:
      - TODO.txt
    dictionary:
      word_lists:
        - en_US
        - ./allowlist.txt
      ignore_case: true
    pipeline:
      regex_code_cleanup:
        type: regex
        options:
          pattern: '(```.*?```|`.*?`)'
          replacement: ''
      regex_url_cleanup:
        type: regex
        options:
          pattern: '\bhttps?://[^\s\)\]]+'
          replacement: ''
