version: "0.34"
dictionary: "en_US"
output: "txt"
files:
  - "**/*.md"
allow:
  - Avalokiteshvara
  - Bodhidharma
  - Buddhanature
  - Dogen
  - Hakuin
  - Hanh
  - Jizo
  - Maitreya
  - Manjushri
  - Nhat
  - Nirvana
  - Obon
  - Rinzai
  - Rohatsu
  - Ryokan
  - Shakyamuni
  - Soto
  - Thich
  - Uchiyama
  - abhidharma
  - amma
  - anatta
  - ango
  - anicca
  - anuttara
  - arhat
  - bodhi
  - bodhisattva
  - buddha-nature
  - daikan
  - dharma
  - dharma-talk
  - dharma-transmission
  - dharmakaya
  - doan
  - dokugo
  - dokusan
  - dukkha
  - fukanzazengi
  - gassho
  - genjokoan
  - han
  - hishiryo
  - ino
  - jikido
  - jukai
  - kaichin
  - karuna
  - keisaku
  - kensho
  - kesa
  - kinhin
  - koan
  - madhyamaka
  - mahaprajna
  - metta
  - mokugyo
  - mu
  - mudita
  - nembutsu
  - no-abode
  - no-mind
  - noabode
  - non-duality
  - nonduality
  - okesa
  - paramita
  - paramitas
  - prajna
  - pratityasamutpada
  - rakusu
  - roshi
  - samadhi
  - samsara
  - sangha
  - sanzen
  - satori
  - seiza
  - sesshin
  - shikantaza
  - shobogenzo
  - shosan
  - shukke
  - shunyata
  - shuso
  - sila
  - six
  - sutra
  - sutras
  - tan
  - tanjo
  - tanto
  - tathagata
  - teisho
  - tenzo
  - tripitaka
  - upaya
  - upekkha
  - vajra
  - vajrayana
  - vinaya
  - vipassana
  - zazen
  - zendo
  - zenki
  - zuise