matrix:
  - name: Markdown
    sources:
      - '**/*.md'
    exclude:
      - TODO.txt
    dictionary:
      word_lists:
        - en_US
        - ./allowlist.txt
    filters:
      - type: wordlist
        ignore_case: true
      - type: regex
        options:
          pattern: '(```.*?```|`.*?`)'
          replacement: ''
      - type: regex
        options:
          pattern: '\bhttps?://[^\s\)\]]+'
          replacement: ''
