matrix:
  - name: Markdown
    sources:
      - '**/*.md'
    exclude:
      - TODO.txt
    dictionary:
      word_lists:
        - en_US
        - ./allowlist.txt
    filters:
      - type: wordlist
        ignore_case: true
    pipeline:
      - name: remove_code
        regex: '(```.*?```|`.*?`)'
        replacement: ''
      - name: remove_urls
        regex: '\bhttps?://[^\s\)\]]+'
        replacement: ''
