---
name: Check Links

"on":
  push:
    branches: [main]
  pull_request:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lychee broken link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --exclude-mail --timeout 20 "**/*.md"
