name: Check Links

on:
  push:
    branches: [main]
  pull_request:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lychee broken link checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --exclude-mail --timeout 20 "**/*.md"
