name: Spell Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  spelling:
    name: Spellcheck Markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.34.0
        with:
          config_path: .spellcheck.yml
